---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: basemaps-create-overview
  namespace: argo
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: source
        value: ""
      - name: max-zoom
        value: ""
      - name: output
        value: ""
  templates:
    - name: main
      dag:
        tasks:
          - name: create-overview
            template: create-overview
            arguments:
              parameters:
                - name: source
                  value: "{{workflow.parameters.source}}"
                - name: max-zoom
                  value: "{{workflow.parameters.max-zoom}}"
                - name: output
                  value: "{{workflow.parameters.output}}"
    - name: create-overview
      inputs:
        parameters:
          - name: source
          - name: max-zoom
          - name: output
      container:
        image: ghcr.io/linz/basemaps/cli:v6.36.0-6-gb92256b0
        command: [node, index.cjs]
        env:
          - name: AWS_ROLE_CONFIG_PATH
            value: s3://linz-bucket-config/config.basemaps.json
        args:
          [
            "-V",
            "create-overview",
            "--source",
            "{{inputs.parameters.source}}",
            "--max-zoom",
            "{{inputs.parameters.max-zoom}}",
            "--output",
            "{{inputs.parameters.output}}",
          ]
