---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: basemaps-create-overview
  namespace: argo
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: source
        value: ""
      - name: output
        value: ""
  templates:
    - name: main
      dag:
        tasks:
          - name: create-overview
            template: create-overview
            arguments:
              parameters:
                - name: source
                  value: "{{workflow.parameters.source}}"
                - name: output
                  value: "{{workflow.parameters.output}}"
    - name: create-overview
      inputs:
        parameters:
          - name: source
          - name: output
      container:
        image: ghcr.io/linz/basemaps/cli:v6.36.0-31-g59a01e66
        resources:
          requests:
            cpu: 3000m
        command: [node, index.cjs]
        env:
          - name: AWS_ROLE_CONFIG_PATH
            value: s3://linz-bucket-config/config.basemaps.json
        args:
          [
            "-V",
            "create-overview",
            "--source",
            "{{inputs.parameters.source}}",
            "--output",
            "{{inputs.parameters.output}}",
          ]
