---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: basemaps-config-create
  namespace: argo
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: version-basemaps-cli
        value: "v6"
      - name: location
        value: "s3://bucket/path/to"
  templateDefaults:
    container:
      imagePullPolicy: Always
  templates:
    - name: main
      dag:
        tasks:
          - name: create-config
            template: create-config
            arguments:
              parameters:
                - name: location
                  value: "{{workflow.parameters.location}}"
    - name: create-config
      inputs:
        parameters:
          - name: location
      container:
        image: ghcr.io/linz/basemaps/cli:{{workflow.parameters.version-basemaps-cli}}
        command: [node, index.cjs]
        env:
          - name: AWS_ROLE_CONFIG_PATH
            value: s3://linz-bucket-config/config.json
        args:
          [
            "-V",
            "create-config",
            "--path",
            "{{inputs.parameters.location}}",
            "--output",
            "/tmp/url",
            "--commit",
          ]
      outputs:
        parameters:
          - name: url
            valueFrom:
              path: "/tmp/url"
