# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-workflows/v3.4.13/api/jsonschema/schema.json

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: basemaps-config-create-5hb23s
  namespace: argo
  labels:
    linz.govt.nz/category: basemaps
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: version_basemaps_cli
        value: 'latest'
      - name: location
        value: 's3://linz-workflows-scratch/2024-02/29-es-wellington-2013-2014-dem-1mvbrl2/flat/'
  templateDefaults:
    container:
      imagePullPolicy: Always
      image: ''
  templates:
    - name: main
      dag:
        tasks:
          - name: create-config
            template: create-config
            arguments:
              parameters:
                - name: location
                  value: '{{workflow.parameters.location}}'
    - name: create-config
      retryStrategy:
        limit: '2'
      inputs:
        parameters:
          - name: location
            description: Location of the imagery to create config for
      container:
        image: ghcr.io/linz/basemaps/cli:{{=sprig.trim(workflow.parameters.version_basemaps_cli)}}
        command: [node, /app/node_modules/.bin/cogify]
        env:
          - name: AWS_ROLE_CONFIG_PATH
            value: s3://linz-bucket-config/config.basemaps.json
        args:
          - 'config'
          - '{{ inputs.parameters.location }}'
          - '--host=https://dev.basemaps.linz.govt.nz'
      outputs:
        parameters:
          - name: url
            description: Basemaps URL to view the imagery
            valueFrom:
              path: '/tmp/cogify/config-url'
          - name: config
            description: Location of the config file
            valueFrom:
              path: '/tmp/cogify/config-path'
