---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: create-all-overviews-v1-
  namespace: argo
spec:
  parallelism: 20
  nodeSelector:
    karpenter.sh/capacity-type: "spot"
  entrypoint: main
  arguments:
    parameters:
      - name: version-basemaps-cli
        value: "v6"
  templates:
    - name: main
      dag:
        tasks:
          - name: list-imagery
            template: list-imagery
          - name: create-overview
            template: create-overview
            arguments:
              parameters:
                - name: source
                  value: "{{item}}"
            depends: "list-imagery"
            withParam: "{{tasks.list-imagery.outputs.parameters.imagery}}"

    - name: list-imagery
      container:
        image: peterevans/curl-jq:latest
        command: [sh, -c]
        args:
          [
            'curl https://raw.githubusercontent.com/linz/basemaps-config/master/config/tileset/aerial.json | jq ''.layers[] | [.["2193"], .["3857"]] | flatten[]'' -r | sort | uniq | grep -v "null" | jq -ncR ''[inputs]'' -r > /tmp/imagery.json',
          ]
      outputs:
        parameters:
          - name: imagery
            valueFrom:
              path: "/tmp/imagery.json"

    - name: create-overview
      inputs:
        parameters:
          - name: source
      container:
        image: ghcr.io/linz/basemaps/cli:{{workflow.parameters.version-basemaps-cli}}
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 3000m
        command: [node, index.cjs]
        env:
          - name: AWS_ROLE_CONFIG_PATH
            value: s3://linz-bucket-config/config.basemaps.json
        args:
          [
            "-V",
            "create-overview",
            "--source",
            "{{inputs.parameters.source}}",
            "--output",
            "{{inputs.parameters.source}}",
          ]
