apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: aws-list-
  annotations: # tell fluentbit we are logging as JSON in this job!
    fluentbit.io/parser: json
spec:
  serviceAccountName: workflow-runner-sa
  entrypoint: main
  arguments:
    parameters:
      - name: uri
        value: "s3://linz-imagery-staging/test/sample/"
  templates:
    - name: main
      dag:
        tasks:
          - name: aws-list
            template: aws-list
            arguments:
              parameters:
                - name: uri
                  value: "{{workflow.parameters.uri}}"
                - name: filter
                  value: ".tiff?$"
          - name: info
            template: info
            arguments:
              parameters:
                - name: file
                  value: "{{item}}"
            depends: "aws-list"
            withParam: "{{tasks.aws-list.outputs.parameters.files}}"

    - name: aws-list
      inputs:
        parameters:
          - name: uri
          - name: filter
      container:
        image: ghcr.io/linz/argo-tasks:v1.0.0-8-g53a2c88
        command: [node, /app/index.cjs]
        env:
          - name: AWS_ROLE_CONFIG_PATH
            value: s3://linz-bucket-config/config-v2.json
        args:
          [
            "list",
            "--verbose",
            "--filter",
            "{{inputs.parameters.filter}}",
            "--group",
            "2",
            "--output",
            "/tmp/file_list.json",
            "{{inputs.parameters.uri}}",
          ]
      outputs:
        parameters:
          - name: files
            valueFrom:
              path: /tmp/file_list.json

    - name: info
      inputs:
        parameters:
          - name: file
      script:
        image: node:18
        command:
          - node
        source: |
          console.log(JSON.stringify({ argv: process.argv, params: JSON.parse('{{inputs.parameters.file}}') }));
