---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: test-vector-etl
  namespace: argo
spec:
  entrypoint: vector-etl
  templateDefaults:
    container:
      imagePullPolicy: Always
  templates:
    - name: vector-etl
      container:
        image: 019359803926.dkr.ecr.ap-southeast-2.amazonaws.com/eks:bm-etl-latest
        resources:
          requests:
            memory: 7.8Gi
            cpu: 15000m
        command: [node, index.cjs]
        env:
          - name: AWS_ROLE_CONFIG_PATH
            value: s3://linz-bucket-config/config.basemaps.json
        args: ["-a", "--commit"]
        outputs:
          artifacts:
            - name: results
              path: /app/.cache/
