---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: basemaps-vector-etl
  namespace: argo
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: target
        value: "linz-basemaps"
        enum:
          - "linz-basemaps"
          - "linz-basemaps-staging"
      - name: create-pull-request
        value: true
        enum:
          - true
          - false
  templateDefaults:
    container:
      imagePullPolicy: Always
  templates:
    - name: main
      dag:
        tasks:
          - name: vector-etl
            template: vector-etl
          - name: create-pr
            template: create-pr
            arguments:
              parameters:
                - name: layer
                  value: "{{tasks.vector-etl.outputs.parameters.layer}}"
            when: "{{workflow.parameters.create-pull-request}} == true"
            depends: "vector-etl"

    - name: vector-etl
      container:
        image: 019359803926.dkr.ecr.ap-southeast-2.amazonaws.com/eks:bm-etl-latest
        resources:
          requests:
            memory: 7.8Gi
            cpu: 15000m
        command: [node, index.cjs]
        env:
          - name: AWS_ROLE_CONFIG_PATH
            value: s3://linz-bucket-config/config.basemaps.json
        args:
          [
            "--all",
            "--target",
            "{{workflow.parameters.target}}",
            "--output",
            "/tmp/",
            "--commit",
          ]
      outputs:
        parameters:
          - name: layer
            valueFrom:
              path: "/tmp/layer.json"

    - name: create-pr
      inputs:
        parameters:
          - name: layer
      container:
        image: ghcr.io/linz/basemaps/cli:latest
        volumeMounts:
          - name: secret-vol
            mountPath: "/root/.ssh/"
        command: [node, index.cjs]
        env:
          - name: GIT_USER_EMAIL
            value: basemaps@linz.govt.nz
          - name: GIT_USER_NAME
            value: basemaps[bot]
        args:
          ["-V", "cog-pr", "--layer", "{{inputs.parameters.layer}}", "--vector"]
  volumes:
    - name: secret-vol
      secret:
        secretName: github-linz-basemaps-config
        defaultMode: 384
