# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-workflows/v3.4.13/api/jsonschema/schema.json

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: basemaps-vector-etl
  namespace: argo
  labels:
    linz.govt.nz/category: basemaps
    linz.govt.nz/data-type: vector
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: version_argo_tasks
        description: Version of the basemaps CLI docker container to use
        value: v2

      - name: target
        description: S3 Bucket to use for storing the output
        value: 'linz-basemaps'
        enum:
          - 'linz-basemaps'
          - 'linz-basemaps-staging'

      - name: create-pull-request
        description: Should a pull request be created in linz/basemaps-config
        value: 'true'
        enum:
          - 'true'
          - 'false'

  templateDefaults:
    container:
      imagePullPolicy: Always
      image: ''

  templates:
    - name: main
      dag:
        tasks:
          - name: vector-etl
            template: vector-etl

          - name: create-pull-request
            template: create-pull-request
            arguments:
              parameters:
                - name: target
                  value: '{{ tasks.vector-etl.outputs.parameters.target }}'
            when: '{{ workflow.parameters.create-pull-request }} == true'
            depends: 'vector-etl'

    - name: vector-etl
      container:
        image: 019359803926.dkr.ecr.ap-southeast-2.amazonaws.com/eks:bm-etl-latest
        resources:
          requests:
            memory: 7.8Gi
            cpu: 15000m
        command: [node, index.cjs]
        env:
          - name: AWS_ROLE_CONFIG_PATH
            value: s3://linz-bucket-config/config.basemaps.json
        args:
          - '--all'
          - '--target={{ workflow.parameters.target }}'
          - '--output=/tmp/'
          - '--commit'
      outputs:
        parameters:
          - name: target
            valueFrom:
              path: '/tmp/target'

    - name: create-pull-request
      inputs:
        parameters:
          - name: target
      container:
        image: 019359803926.dkr.ecr.ap-southeast-2.amazonaws.com/argo-tasks:{{ workflow.parameters.version_argo_tasks }}
        command: [node, /app/index.js]
        env:
          - name: AWS_ROLE_CONFIG_PATH
            value: s3://linz-bucket-config/config.basemaps.json
          - name: GITHUB_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: github-linz-li-bot-pat
                key: pat
        args:
          - 'bmc'
          - 'create-pr'
          - '--target={{ inputs.parameters.target }}'
          - '--vector'
