---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: stac-validate-v1.0.0-40
  namespace: argo
spec:
  nodeSelector:
    karpenter.sh/capacity-type: "spot"
  entrypoint: main
  arguments:
    parameters:
      - name: stac-file-path
        value: "s3://linz-imagery-staging/test/stac-validate/collection.json"
  templates:
    - name: main
      dag:
        tasks:
          - name: stac-validate
            template: stac-validate
            arguments:
              parameters:
                - name: stac-file-path
                  value: "{{workflow.parameters.stac-file-path}}"
              artifacts:
                - name: stac-result
                  raw:
                    data: "{ { tasks.stac-validate.outputs.result } }"
    - name: stac-validate
      inputs:
        parameters:
          - name: stac-file-path
      container:
        image: ghcr.io/linz/argo-tasks:v1.0.0-40-g10e90df
        command: [node, /app/index.js]
        env:
          - name: AWS_ROLE_CONFIG_PATH
            value: s3://linz-bucket-config/config.json
        args:
          [
            "stac-validate",
            "--recursive",
            "{{inputs.parameters.stac-file-path}}",
          ]
