# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-workflows/v3.5.5/api/jsonschema/schema.json

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: stac-validate-parallel
  labels:
    linz.govt.nz/category: stac
spec:
  parallelism: 20
  nodeSelector:
    karpenter.sh/capacity-type: 'spot'
  entrypoint: main
  arguments:
    parameters:
      - name: version_argo_tasks
        value: 'v4'
      - name: uri
        description: 'Path(s) to the STAC file(s).'
        value: 's3://linz-imagery-staging/test/stac-validate/'
      - name: include
        value: 'collection.json$'
      - name: checksum_assets
        description: 'Validate the file:checksum of each asset if it exists'
        value: 'false'
        enum:
          - 'true'
          - 'false'
      - name: checksum_links
        description: 'Validate the file:checksum of each link if it exists'
        value: 'true'
        enum:
          - 'false'
          - 'true'
  templateDefaults:
    container:
      imagePullPolicy: Always
      image: ''
  templates:
    - name: main
      dag:
        tasks:
          - name: aws-list-collections
            template: aws-list-collections
          - name: stac-validate-collections
            templateRef:
              name: tpl-at-stac-validate
              template: main
            arguments:
              parameters:
                - name: uri
                  value: '{{item}}'
                - name: checksum
                  value: '{{workflow.parameters.checksum}}'
            depends: aws-list-collections
            withParam: '{{tasks.aws-list-collections.outputs.parameters.files}}'
    - name: aws-list-collections
      container:
        image: '019359803926.dkr.ecr.ap-southeast-2.amazonaws.com/argo-tasks:{{=sprig.trim(workflow.parameters.version_argo_tasks)}}'
        command: [node, /app/index.js]
        env:
          - name: AWS_ROLE_CONFIG_PATH
            value: s3://linz-bucket-config/config.json
        args:
          [
            'list',
            '--verbose',
            '--include',
            '{{=sprig.trim(workflow.parameters.include)}}',
            '--group',
            '1',
            '--output',
            '/tmp/file_list.json',
            '{{=sprig.trim(workflow.parameters.uri)}}',
          ]
      outputs:
        parameters:
          - name: files
            valueFrom:
              path: /tmp/file_list.json
