version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: "docker"
  directory: "/.github/workflows"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  groups:
    aws-sdk:
      patterns:
        - "@aws-sdk/*"
    aws-cdk:
      patterns:
        - "@aws-cdk/*"
        - "aws-cdk"
        - "aws-cdk-lib"
        - "cdk8s"
        - "cdk8s-cli"
        - "cdk8s-plus-27"
        - "constructs"
  ignore:
    - dependency-name: "@aws-sdk/*"
      update-types: ["version-update:semver-patch"]
    - dependency-name: "@types/node"
      update-types: ["version-update:semver-patch"]
