# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-workflows/v3.4.13/api/jsonschema/schema.json

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: imagery-standardising-publish-import-
  namespace: argo
  labels:
    linz.govt.nz/category: raster
    linz.govt.nz/data-type: raster
spec:
  parallelism: 50
  nodeSelector:
    karpenter.sh/capacity-type: 'spot'
  entrypoint: main
  synchronization:
    semaphore:
      configMapKeyRef:
        name: semaphores
        key: bulk
  workflowMetadata:
    labelsFrom:
      linz.govt.nz/ticket:
        expression: workflow.parameters.ticket
      linz.govt.nz/region:
        expression: workflow.parameters.region
  arguments:
    parameters:
      - name: ticket
        value: ''
      - name: region
        value: ''
      - name: source
        value: ''
      - name: cutline # optional standardising cutline
        value: ''
      - name: collection_id # optional
        value: ''
      - name: location # optional
        value: ''
      - name: event # optional
        value: ''
      - name: historic_survey_number # optional
        value: ''
      - name: compression
        value: 'webp'
      - name: source_epsg
        value: '2193'
      - name: target_epsg
        value: '2193'
      - name: group
        value: '50'
      - name: copy_option
        value: '--no-clobber'
      - name: include
        value: '.tiff?$'
      - name: transform
        value: 'f'
      - name: validate
        value: 'true'
      - name: retile
        value: 'false'
      - name: lifecycle
        value: 'completed'
      - name: version_argo_tasks
        value: 'v2'
      - name: version_basemaps_cli
        value: 'v6'
      - name: version_topo_imagery
        value: 'v3'
  templateDefaults:
    container:
      imagePullPolicy: Always
      image: ''
  templates:
    - name: main
      steps:
        - - name: standardise
            templateRef:
              name: imagery-standardising
              template: main
            arguments:
              parameters:
                - name: source
                  value: '{{workflow.parameters.source}}'
        - - name: publish
            templateRef:
              name: publish-copy
              template: main
            arguments:
              parameters:
                - name: source
                  value: '{{steps.standardise.outputs.parameters.target}}flat/'
                - name: include
                  value: '.tiff?$|.json$'
                - name: group
                  value: '1000'
                - name: group_size
                  value: '100Gi'
        # - - name: import # uncomment this stanza for basemaps imagery import and amend as necessary. All other inputs should be workflow parameters
        #     templateRef:
        #       name: basemaps-imagery-import-cogify
        #       template: main
        #     arguments:
        #       parameters:
        #         - name: version_argo_tasks
        #           value: 'v2'
        #         - name: version_basemaps_cli
        #           value: 'v6'
        #         - name: source
        #           value: "{{workflow.parameters.target}}"
        #         - name: target
        #           value: "linz-basemaps" # change to "linz-basemaps-staging" for staging environment
        #         - name: cutline
        #           value: "s3://linz-basemaps-source/cutline/2020-05-07-cutline-nz-coasts-rural-and-urban.geojson"
        #         - name: create_pull_request
        #           value: "aerial" # change as required
        #         - name: category
        #           value: "Rural Aerial Photos" # change as required
  volumes:
    - name: ephemeral
      emptyDir: {}
