---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: imagery-extent-
spec:
  serviceAccountName: workflow-runner-sa
  podGC:
    strategy: OnPodCompletion # Delete pod once its finished
  nodeSelector:
    karpenter.sh/capacity-type: "spot"
  entrypoint: main
  arguments:
    parameters:
      - name: uri
        value: s3://linz-imagery-staging/RGB/ecan/2022/04/ashburton-urban/Ashburton_Town/03_RGB_Tiff_AOI/
      - name: filter
        value: "BY21_500_067044.tif"
  templates:
    - name: main
      dag:
        tasks:
          - name: aws-list
            template: aws-list
            arguments:
              parameters:
                - name: uri
                  value: "{{workflow.parameters.uri}}"
                - name: filter
                  value: "{{workflow.parameters.filter}}"
          - name: get-extent
            template: get-extent
            arguments:
              parameters:
                - name: file
                  value: "{{item}}"
            depends: aws-list
            withParam: "{{tasks.aws-list.outputs.parameters.files}}"
          - name: message
            template: message
            arguments:
              parameters:
                - name: file
                  value: "{{item}}"
            depends: get-extent
            withParam: "{{tasks.get-extent.artifacts.output-files}}"
    - name: aws-list
      inputs:
        parameters:
          - name: uri
          - name: filter
      container:
        resources:
          requests:
            memory: 2Gi
            cpu: 2000m
        image: ghcr.io/linz/basemaps/cli:v6.29.0-3-gb4dec98c
        command: [node, index.cjs]
        args:
          [
            "-V",
            "list",
            "--filter",
            "{{inputs.parameters.filter}}",
            "--output",
            "/tmp/file_list.json",
            "--config",
            "linz-bucket-config",
            "{{inputs.parameters.uri}}",
          ]
      outputs:
        parameters:
          - name: files
            valueFrom:
              path: /tmp/file_list.json
    - name: get-extent
      inputs:
        parameters:
          - name: file
      container:
        image: ghcr.io/linz/topo-imagery:v0.2.0-14-g5387093
        command:
          - python
          - "/app/create_polygons.py"
        args:
          - "--source"
          - "{{inputs.parameters.file}}"
        outputs:
        artifacts:
        - name: output-files
          path: /tmp/file_list.json
    - name: message
      inputs:
        parameters:
        - name: message
      script:
        image: alpine:latest
        command: [sh]
        source: |
          echo "{{inputs.parameters.file}}"
