---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: imagery-extent-
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: uri
        value: s3://linz-imagery-staging/RGB/ecan/2022/04/ashburton-urban/Ashburton_Town/03_RGB_Tiff_AOI/
  templates:
    - name: main
      dag:
        tasks:
          - name: aws-list
            template: aws-list
            arguments:
              parameters:
                - name: uri
                  value: "{{workflow.parameters.uri}}"
                - name: filter
                  value: "**/BY21_500_03001*.tif"
          - name: get-extent
            template: get-extent
            arguments:
              parameters:
                - name: file
                  value: "{{item}}"
            depends: aws-list
            withParam: "{{tasks.aws-list.outputs.parameters.files}}"
    - name: aws-list
      inputs:
        parameters:
          - name: uri
          - name: filter
      container:
        image: ghcr.io/linz/argo-tasks:v1.0.0-8-g53a2c88
        command: [node, /app/index.cjs]
        env:
          - name: AWS_ROLE_CONFIG_PATH
            value: s3://linz-bucket-config/config-v2.json
        args:
          [
            "list",
            "--verbose",
            "--filter",
            "{{inputs.parameters.filter}}",
            "--group",
            "100",
            "--output",
            "/tmp/file_list.json",
            "--config",
            "linz-bucket-config",
            "{{inputs.parameters.uri}}",
          ]
      outputs:
        parameters:
          - name: files
            valueFrom:
              path: /tmp/file_list.json
    - name: get-extent
      inputs:
        parameters:
          - name: file
      container:
        image: ghcr.io/linz/topo-imagery:v0.2.0-30-g25a85c1
        command:
          - python
          - "/app/scripts/standardising.py"
        args:
          - "--gdal-command"
          - gdalinfo -json
          - "--gdal-input"
          - "{{inputs.parameters.file}}"
      outputs:
        parameters:
          - name: extent
            valueFrom:
              path: "/tmp/extent.json"
