---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: publish-copy
  namespace: argo
spec:
  parallelism: 50
  nodeSelector:
    karpenter.sh/capacity-type: "spot"
  entrypoint: main
  arguments:
    parameters:
      - name: version-argo-tasks
        value: "v2"
      - name: source
        value: "s3://linz-imagery-staging/test/sample/"
      - name: target
        value: "s3://linz-imagery-staging/test/sample_target/"
      - name: include
        value: ".tiff?$|.json$|.tfw$"
      - name: copy-option
        value: "--no-clobber"
        enum:
          - "--no-clobber"
          - "--force"
          - "--force-no-clobber"
  templateDefaults:
    container:
      imagePullPolicy: Always
  templates:
    - name: main
      inputs:
        parameters:
          - name: source
          - name: target
          - name: include
          - name: copy-option
          - name: version-argo-tasks
      dag:
        tasks:
          - name: create-manifest
            template: create-manifest
            arguments:
              parameters:
                - name: source
                  value: "{{inputs.parameters.source}}"
                - name: target
                  value: "{{inputs.parameters.target}}"
                - name: include
                  value: "{{inputs.parameters.include}}"
                - name: version-argo-tasks
                  value: "{{inputs.parameters.version-argo-tasks}}"
          - name: copy
            template: copy
            arguments:
              parameters:
                - name: copy-option
                  value: "{{inputs.parameters.copy-option}}"
                - name: file
                  value: "{{item}}"
                - name: version-argo-tasks
                  value: "{{inputs.parameters.version-argo-tasks}}"
            depends: "create-manifest"
            withParam: "{{tasks.create-manifest.outputs.parameters.files}}"
    - name: create-manifest
      inputs:
        parameters:
          - name: source
          - name: target
          - name: include
          - name: version-argo-tasks
      container:
        image: "ghcr.io/linz/argo-tasks:{{=sprig.trim(inputs.parameters['version-argo-tasks'])}}"
        command: [node, /app/index.js]
        env:
          - name: AWS_ROLE_CONFIG_PATH
            value: s3://linz-bucket-config/config.json
        args:
          [
            "create-manifest",
            "--verbose",
            "--include",
            "{{=sprig.trim(inputs.parameters.include)}}",
            "--group",
            "1000",
            "--group-size",
            "100Gi",
            "--output",
            "/tmp/file_list.json",
            "--target",
            "{{=sprig.trim(inputs.parameters.target)}}",
            "{{=sprig.trim(inputs.parameters.source)}}",
          ]
      outputs:
        parameters:
          - name: files
            valueFrom:
              path: /tmp/file_list.json
    - name: copy
      retryStrategy:
        limit: "2"
      inputs:
        parameters:
          - name: copy-option
          - name: version-argo-tasks
          - name: file
      container:
        image: "ghcr.io/linz/argo-tasks:{{=sprig.trim(inputs.parameters['version-argo-tasks'])}}"
        resources:
          requests:
            memory: 7.8Gi
            cpu: 2000m
        command: [node, /app/index.js]
        env:
          - name: AWS_ROLE_CONFIG_PATH
            value: s3://linz-bucket-config/config-write.imagery.json,s3://linz-bucket-config/config.json
        args:
          [
            "copy",
            "{{inputs.parameters.copy-option}}",
            "{{inputs.parameters.file}}",
          ]
