---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-amfage-publish-copy-gh-
  namespace: argo
spec:
  parallelism: 50
  nodeSelector:
    karpenter.sh/capacity-type: "spot"
  entrypoint: main
  arguments:
    parameters:
      - name: version-argo-tasks
        value: "latest"
      - name: source
        # value: "s3://linz-imagery-staging/test/sample/"
        value: "s3://linz-workflow-artifacts/2023-04/25-ispi-manawatu-whanganui-2010-2011-0-4m-tttsb/flat/"
      - name: target
        # value: "s3://linz-imagery-staging/test/sample_target/"
        value: "s3://linz-imagery/manawatu-whanganui/manawatu-whanganui_2010-2011_0.4m/rgb/2193/"
      - name: include
        value: ".tiff?$|.json$|.tfw$"
      - name: copy-option
        value: "--no-clobber"
        enum:
          - "--no-clobber"
          - "--force"
          - "--force-no-clobber"
      - name: group
        value: "1000"
      - name: group-size
        value: "100Gi"
      - name: transform
        value: "f"
  templateDefaults:
    container:
      imagePullPolicy: Always
  templates:
    - name: main
      inputs:
        parameters:
          - name: source
          - name: include
          - name: group
          - name: group-size
          - name: target
      dag:
        tasks:
          - name: create-manifest-linz-imagery
            template: create-manifest
            arguments:
              parameters:
                - name: source
                  value: "{{inputs.parameters.source}}"
                - name: target
                  value: "{{workflow.parameters.target}}"
                - name: include
                  value: "{{inputs.parameters.include}}"
                - name: exclude
                  value: "collection.json$"
                - name: group
                  value: "{{inputs.parameters.group}}"
                - name: group-size
                  value: "{{inputs.parameters.group-size}}"
                - name: version-argo-tasks
                  value: "{{workflow.parameters.version-argo-tasks}}"
            when: "{{=sprig.contains('s3://linz-imagery/', workflow.parameters.target)}}"
          - name: create-manifest
            template: create-manifest
            arguments:
              parameters:
                - name: source
                  value: "{{inputs.parameters.source}}"
                - name: target
                  value: "{{workflow.parameters.target}}"
                - name: include
                  value: "{{inputs.parameters.include}}"
                - name: exclude
                  value: ""
                - name: group
                  value: "{{inputs.parameters.group}}"
                - name: group-size
                  value: "{{inputs.parameters.group-size}}"
                - name: version-argo-tasks
                  value: "{{workflow.parameters.version-argo-tasks}}"
            depends: "create-manifest-linz-imagery.Skipped"
          - name: copy-linz-imagery
            template: dummy-copy
            arguments:
              parameters:
                - name: copy-option
                  value: "{{workflow.parameters.copy-option}}"
                - name: file
                  value: "{{item}}"
                - name: version-argo-tasks
                  value: "{{workflow.parameters.version-argo-tasks}}"
            depends: "create-manifest-linz-imagery"
            withParam: "{{tasks.create-manifest-linz-imagery.outputs.parameters.files}}"
          - name: copy
            template: copy
            arguments:
              parameters:
                - name: copy-option
                  value: "{{workflow.parameters.copy-option}}"
                - name: file
                  value: "{{item}}"
                - name: version-argo-tasks
                  value: "{{workflow.parameters.version-argo-tasks}}"
            depends: "create-manifest"
            withParam: "{{tasks.create-manifest.outputs.parameters.files}}"
          - name: push-to-github
            template: push-to-github
            arguments:
              parameters:
                - name: source
                  value: "{{inputs.parameters.source}}"
            depends: "copy-linz-imagery"
    - name: create-manifest
      inputs:
        parameters:
          - name: source
          - name: include
          - name: exclude
          - name: group
          - name: group-size
      container:
        image: "019359803926.dkr.ecr.ap-southeast-2.amazonaws.com/eks:argo-tasks-{{=sprig.trim(workflow.parameters['version-argo-tasks'])}}"
        command: [node, /app/index.js]
        env:
          - name: AWS_ROLE_CONFIG_PATH
            value: s3://linz-bucket-config/config.json
        args:
          [
            "create-manifest",
            "--verbose",
            "--include",
            "{{=sprig.trim(inputs.parameters.include)}}",
            "--exclude",
            "{{inputs.parameters.exclude}}",
            "--group",
            "{{=sprig.trim(inputs.parameters.group)}}",
            "--group-size",
            "{{=sprig.trim(inputs.parameters['group-size'])}}",
            "--output",
            "/tmp/file_list.json",
            "--target",
            "{{=sprig.trim(workflow.parameters.target)}}",
            "{{=sprig.trim(inputs.parameters.source)}}",
            "--transform",
            "{{=sprig.trim(workflow.parameters.transform)}}",
          ]
      outputs:
        parameters:
          - name: files
            valueFrom:
              path: /tmp/file_list.json
    - name: copy
      retryStrategy:
        limit: "2"
      inputs:
        parameters:
          - name: file
      container:
        image: "019359803926.dkr.ecr.ap-southeast-2.amazonaws.com/eks:argo-tasks-{{=sprig.trim(workflow.parameters['version-argo-tasks'])}}"
        resources:
          requests:
            memory: 7.8Gi
            cpu: 2000m
        command: [node, /app/index.js]
        env:
          - name: AWS_ROLE_CONFIG_PATH
            value: s3://linz-bucket-config/config-write.imagery.json,s3://linz-bucket-config/config.json
        args:
          [
            "copy",
            "{{workflow.parameters.copy-option}}",
            "{{inputs.parameters.file}}",
          ]
    - name: dummy-copy
      inputs:
        parameters:
          - name: file
      script:
        image: "019359803926.dkr.ecr.ap-southeast-2.amazonaws.com/eks:argo-tasks-{{=sprig.trim(workflow.parameters['version-argo-tasks'])}}"
        command: [bash]
        source: |
          echo {{inputs.parameters.file}}
        env:
          - name: AWS_ROLE_CONFIG_PATH
            value: s3://linz-bucket-config/config-write.imagery.json,s3://linz-bucket-config/config.json
    - name: push-to-github
      retryStrategy:
        limit: "2"
      inputs:
        parameters:
          - name: source
      container:
        image: "019359803926.dkr.ecr.ap-southeast-2.amazonaws.com/eks:argo-tasks-{{=sprig.trim(workflow.parameters['version-argo-tasks'])}}"
        resources:
          requests:
            memory: 7.8Gi
            cpu: 2000m
        env:
          - name: AWS_ROLE_CONFIG_PATH
            value: s3://linz-bucket-config/config.json
          - name: GIT_AUTHOR_NAME
            value: "Imagery[bot]"
          - name: GIT_AUTHOR_EMAIL
            value: "imagery@linz.govt.nz"
        command: [node, /app/index.js]
        args:
          [
            "stac",
            "github-import",
            "--source",
            "{{=sprig.trim(inputs.parameters.source)}}",
            "--target",
            "{{=sprig.trim(workflow.parameters.target)}}",
            "--repo-name",
            "linz/imagery-test",
          ]
  volumes:
    - name: secret-vol
      secret:
        secretName: github-linz-imagery-test
        defaultMode: 384
