---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: standardising-publish-
  entrypoint: main
  arguments:
    parameters:
      ## The following parameters MUST be specified when submitting (values are examples only)
      # -p source="s3://linz-imagery-staging/test/sample/"
      # -p target="s3://linz-imagery-staging/test/sample_target/"
      # -p title="*Region/District/City* *GSD* *Urban/Rural* Aerial Photos (*Year-Year*)"
      # -p description="Orthophotography within the *Region Name* region captured in the *Year*-*Year* flying season."
      # -p start-datetime="YYYY-MM-DD"
      # -p end-datetime="YYYY-MM-DD"
      # -p scale=""
      # -p compression="webp"

      ## The cutline parameter CAN be specified when submitting (value is example only)
      # -p cutline="s3://linz-imagery-staging/test/sample/sample_cutline.fgb"

      ## The following parameters CAN be specified when submitting to override the defaults below
      - name: standardise-copy-option
        value: "--no-clobber"
      - name: standardise-include
        value: ".tiff?$"
      - name: publish-copy-option
        value: "--no-clobber"
      - name: publish-include
        value: ".tiff?$|.json$"

  templates:
    - name: main
      steps:
        - - name: standardise
            templateRef:
              name: test-amfage-imagery-standardising-v1
              template: main
            arguments:
              parameters:
                - name: version-argo-tasks
                  value: "v2"
                - name: version-basemaps-cli
                  value: "v6"
                - name: version-topo-imagery
                  value: "v0"
                - name: include
                  value: "{{workflow.parameters.standardise-include}}"
                - name: copy-option
                  value: "{{workflow.parameters.standardise-copy-option}}"
                - name: group
                  value: "50"
        - - name: publish
            templateRef:
              name: test-amfage-publish-copy-v1
              template: main
              depends: standardise
            arguments:
              parameters:
                - name: version-argo-tasks
                  value: "v2"
                - name: source
                  value: "{{steps.standardise.outputs.parameters.target}}"
                - name: target
                  value: "{{workflow.parameters.target}}"
                - name: include
                  value: "{{workflow.parameters.publish-include}}"
                - name: copy-option
                  value: "{{workflow.parameters.publish-copy-option}}"
