---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: standardising-publish-
  namespace: argo
spec:
  parallelism: 50
  nodeSelector:
    karpenter.sh/capacity-type: "spot"
  entrypoint: main
  synchronization:
    semaphore:
      configMapKeyRef:
        name: semaphores
        key: standardising
  arguments:
    parameters:
      - name: target # mandatory parameter
      # - name: source # mandatory parameter
      # - name: title # mandatory parameter
      # - name: description # mandatory parameter
      # - name: start-datetime # mandatory parameter
      # - name: end-datetime # mandatory parameter
      # - name: scale # mandatory parameter
      # - name: cutline # optional parameter
      - name: compression # optional parameter, default can be overridden on the command line
        value: "webp"
      - name: group # optional parameter, default can be overridden on the command line
        value: "50"
      - name: copy-option # optional parameter, default can be overridden on the command line
        value: "--no-clobber"
      - name: include # optional parameter, default can be overridden on the command line
        value: ".tiff?$"
      - name: publish-copy-option # optional parameter, default can be overridden on the command line
        value: "--no-clobber"
      - name: publish-include # optional parameter, default can be overridden on the command line
        value: ".tiff?$|.json$"
      - name: version-argo-tasks # optional parameter, default can be overridden on the command line
        value: "v2"
      - name: version-basemaps-cli # optional parameter, default can be overridden on the command line
        value: "v6"
      - name: version-topo-imagery # optional parameter, default can be overridden on the command line
        value: "v0"
      - name: publish-version-argo-tasks # optional parameter, default can be overridden on the command line
        value: "v2"
  templateDefaults:
    container:
      imagePullPolicy: Always
  templates:
    - name: main
      steps:
        - - name: standardise
            templateRef:
              name: imagery-standardising
              template: main
        - - name: publish
            templateRef:
              name: publish-copy
              template: main
            arguments:
              parameters:
                - name: version-argo-tasks
                  value: "{{workflow.parameters.publish-version-argo-tasks}}"
                - name: source
                  value: "{{steps.standardise.outputs.parameters.target}}flat/"
                - name: target
                  value: "{{workflow.parameters.target}}"
                - name: include
                  value: "{{workflow.parameters.publish-include}}"
                - name: copy-option
                  value: "{{workflow.parameters.publish-copy-option}}"
  volumes:
    - name: ephemeral
      emptyDir: {}
