---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: imagery-standardise-v0.2.0-20
spec:
  parallelism: 20
  nodeSelector:
    karpenter.sh/capacity-type: "spot"
  entrypoint: main
  arguments:
    parameters:
      - name: source
        value: "s3://linz-imagery-staging/test/sample/"
      - name: filter
        value: ".tiff?$"
      - name: group
        value: 10
  templates:
    - name: main
      dag:
        tasks:
          - name: aws-list
            template: aws-list
            arguments:
              parameters:
                - name: source
                  value: "{{workflow.parameters.source}}"
                - name: filter
                  value: "{{workflow.parameters.filter}}"
          - name: standardise
            template: standardise
            arguments:
              parameters:
                - name: file
                  value: "{{item}}"
            depends: "aws-list"
            withParam: "{{tasks.aws-list.outputs.parameters.files}}"
          - name: get-location
            template: get-location
          - name: create-config
            arguments:
              parameters:
                - name: location
                  value: "{{tasks.get-location.outputs.parameters.location}}"
            template: create-config
            depends: "get-location && standardise"
    - name: aws-list
      inputs:
        parameters:
          - name: source
          - name: filter
      container:
        image: ghcr.io/linz/basemaps/cli:v6.34.0
        command: [node, index.cjs]
        args:
          [
            "-V",
            "list",
            "--filter",
            "{{inputs.parameters.filter}}",
            "--group",
            "{{workflow.parameters.group}}",
            "--output",
            "/tmp/file_list.json",
            "--config",
            "s3://linz-bucket-config/config.json",
            "{{inputs.parameters.source}}",
          ]
      outputs:
        parameters:
          - name: files
            valueFrom:
              path: /tmp/file_list.json
    - name: standardise
      retryStrategy:
        limit: "2"
      nodeSelector:
        karpenter.sh/capacity-type: "spot"
      inputs:
        parameters:
          - name: file
      container:
        image: ghcr.io/linz/topo-imagery:v0.2.0-20-ged4d623
        resources:
          requests:
            memory: 3.9Gi
            cpu: 2000m
            ephemeral-storage: 3Gi
        volumeMounts:
          - name: ephemeral
            mountPath: "/tmp"
        command:
          - python
          - "/app/standardising.py"
        args:
          - "--source"
          - "{{inputs.parameters.file}}"
      outputs:
        artifacts:
          - name: standardised_tiffs
            path: /tmp/
            archive:
              none: {}
    - name: get-location
      script:
        image: node:alpine
        command: [node]
        source: |
          const fs = require('fs');
          const loc = JSON.parse(process.env['ARGO_TEMPLATE']).archiveLocation.s3;
          const key = loc.key.replace('{{pod.name}}','');
          fs.writeFileSync('/tmp/location', `s3://${loc.bucket}/${key}`);
      outputs:
        parameters:
          - name: location
            valueFrom:
              path: "/tmp/location"
    - name: create-config
      inputs:
        parameters:
          - name: location
      container:
        image: ghcr.io/linz/basemaps/cli:v6.34.0
        command: [node, index.cjs]
        args:
          [
            "-V",
            "create-config",
            "--path",
            "{{inputs.parameters.location}}",
            "--config",
            "s3://linz-bucket-config/config.json",
            "--commit",
          ]
  volumes:
    - name: ephemeral
      emptyDir: {}
