apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: topo-imagery-test-script-
spec:
  serviceAccountName: workflow-runner-sa
  podGC:
    strategy: OnPodCompletion # Delete pod once its finished
  entrypoint: test-script
  templates:
    - name: test-script
      script:
        image: ghcr.io/linz/topo-imagery:v0.2.0-56-g786b11e
        command: [python]
        source: |
          import sys

          # Because Argo Workflow executes the script under "/argo/staging/script"
          sys.path.append("/app/scripts/")

          # Put your code below
