# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-workflows/v3.5.5/api/jsonschema/schema.json

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: tpl-gdalmerge
  labels:
    linz.govt.nz/category: util
spec:
  nodeSelector:
    karpenter.sh/capacity-type: 'spot'
  entrypoint: main
  workflowMetadata:
    labelsFrom:
      linz.govt.nz/ticket:
        expression: inputs.parameters.ticket
  podMetadata:
    labels:
      linz.govt.nz/category: raster
      linz.govt.nz/data-type: raster
      linz.govt.nz/ticket: '{{inputs.parameters.ticket}}'
  templates:
    - name: main
      retryStrategy:
        expression: 'false'
      container:
        image: 019359803926.dkr.ecr.ap-southeast-2.amazonaws.com/topo-imagery:{{=sprig.trim(inputs.parameters.version_topo_imagery)}}
        imagePullPolicy: Always
        command: [gdal_merge.py]
        args:
          [
            '-of',
            'GTiff',
            '-ps',
            '1',
            '-1',
            '-co',
            'COMPRESS=lerc',
            '-co',
            'MAX_Z_ERROR=0',
            '-co',
            'NUM_THREADS=ALL_CPUS',
            '-o',
            '{{inputs.parameters.merged_filename}}',
            '{{inputs.parameters.base_filename}}',
            '{{inputs.parameters.additional_filename}}',
          ]
        resources:
          requests:
            memory: 12.0Gi
      inputs:
        parameters:
          - name: base_filename
            description: 'File to use as base layer (use /vsis3/ paths instead of s3://), e.g. "/vsis3_streaming/bucket/8m/CB13.tiff"'
          - name: additional_filename
            description: 'File to use as top layer (use /vsis3/ paths instead of s3://), e.g. "/vsis3_streaming/bucket/1m/CB13.tiff". Use VRT files to layer multiple files.'
          - name: version_topo_imagery
            description: 'Specify a version of the topo-imagery image to use, e.g. "v7" or "latest"'
            default: 'v7'
          - name: ticket
            description: 'Ticket ID, e.g. "LI-1570"'
            default: ''
          - name: merged_filename
            description: 'Optional file name for output file, e.g. "CB13.tiff"'
            default: 'merge_output.tiff'
      outputs:
        artifacts:
          - name: merged_tiff
            archive:
              none: {}
            path: '{{inputs.parameters.merged_filename}}'
