apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  # Template for copying a manifest of files between two locations
  # See https://github.com/linz/argo-tasks#copy
  name: tpl-copy
spec:
  templateDefaults:
    container:
      imagePullPolicy: Always
  entrypoint: main
  templates:
    - name: main
      retryStrategy:
        limit: "2"
      inputs:
        parameters:
          - name: file
            description: Path to the manifest file detailing source and target

          - name: version-argo-tasks
            description: version of argo-tasks to use
            default: "v2"

          - name: copy-option
            description: --no-clobber Skip overwriting existing files. --force Overwrite all files. --force-no-clobber Overwrite only changed files, skip unchanged files.
            default: "--no-clobber"
            enum:
              - "--no-clobber"
              - "--force"
              - "--force-no-clobber"

          - name: aws-role-config-path
            description: The path(s) to the aws configs that enable writing to buckets
            default: "s3://linz-bucket-config/config-write.imagery.json,s3://linz-bucket-config/config-write.elevation.json,s3://linz-bucket-config/config-write.topographic.json"

      container:
        image: "019359803926.dkr.ecr.ap-southeast-2.amazonaws.com/eks:argo-tasks-{{=sprig.trim(workflow.parameters['version-argo-tasks'])}}"
        resources:
          requests:
            memory: 7.8Gi
            cpu: 2000m
        command: [node, /app/index.js]
        env:
          - name: AWS_ROLE_CONFIG_PATH
            value: "s3://linz-bucket-config/config.json,{{inputs.parameters.aws-role-config-path}}"
        args:
          [
            "copy",
            "{{inputs.parameters.copy-option}}",
            "{{inputs.parameters.file}}",
          ]
