apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  # Template for creating a manifest
  # See TODO Github link
  name: tpl-create-manifest
spec:
  templateDefaults:
    container:
      imagePullPolicy: Always
  entrypoint: main
  templates:
    - name: main
      inputs:
        parameters:
          - name: source
            description: location of data to publish

          - name: target
            description: location to publish data to

          - name: version-argo-tasks
            description: version of argo-tasks to use
            default: "v2"

          - name: include
            description: TODO
            default: ".tiff?$|.json$|.tfw$"

          - name: exclude
            description: TODO
            default: ""

          - name: copy-option
            description: TODO
            default: "--no-clobber"
            enum:
              - "--no-clobber"
              - "--force"
              - "--force-no-clobber"

          - name: group
            description: TODO
            default: "1000"

          - name: group-size
            description: TODO
            default: "100Gi"

          - name: transform
            description: TODO
            default: "f"

      outputs:
        parameters:
          - name: files
            valueFrom:
              path: /tmp/file_list.json

      container:
        image: "019359803926.dkr.ecr.ap-southeast-2.amazonaws.com/eks:argo-tasks-{{=sprig.trim(inputs.parameters['version-argo-tasks'])}}"
        command: [node, /app/index.js]
        env:
          - name: AWS_ROLE_CONFIG_PATH
            value: s3://linz-bucket-config/config.json
        args:
          [
            "create-manifest",
            "--verbose",
            "--include",
            "{{=sprig.trim(inputs.parameters.include)}}",
            "--exclude",
            "{{inputs.parameters.exclude}}",
            "--group",
            "{{=sprig.trim(inputs.parameters.group)}}",
            "--group-size",
            "{{=sprig.trim(inputs.parameters['group-size'])}}",
            "--output",
            "/tmp/file_list.json",
            "--target",
            "{{=sprig.trim(inputs.parameters.target)}}",
            "{{=sprig.trim(inputs.parameters.source)}}",
            "--transform",
            "{{=sprig.trim(inputs.parameters.transform)}}",
          ]
