apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: tpl-at-format
spec:
  templateDefaults:
    container:
      imagePullPolicy: Always
  entrypoint: main
  templates:
    - name: main
      inputs:
        parameters:
          - name: source
            description: Path to format files from
          - name: target
            description: (Optional) Target directory (testing)
            default: ""
          - name: version
            description: argo-task Container version to use
            default: "v2"

      container:
        image: "019359803926.dkr.ecr.ap-southeast-2.amazonaws.com/eks:argo-tasks-{{= inputs.parameters.version }}"
        command: [node, /app/index.js]
        env:
          - name: AWS_ROLE_CONFIG_PATH
            value: s3://linz-bucket-config/config.json
        args:
          - "pretty-print"
          - "{{= inputs.parameters.source }}"
          - "{{= sprig.empty(inputs.parameters.target) ? '' : '--target=' + inputs.parameters.target }}"
