apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  # Template for Formatting and Pushing STAC Collections to Github
  # See https://github.com/linz/argo-tasks#stac-github-import
  name: tpl-push-to-github
spec:
  templateDefaults:
    container:
      imagePullPolicy: Always
  entrypoint: main
  templates:
    - name: main
      retryStrategy:
        limit: "2"
      inputs:
        parameters:
          - name: source
            description: location where the source collection.json file is

          - name: target
            description: location where the destination collection.json file will be

          - name: version-argo-tasks
            description: version of argo-tasks to use
            default: "v2"

          - name: repository
            description: Repository Name (only used when identified that push to GitHub is required)
            default: "elevation"
            enum:
              - "elevation"
              - "imagery"

      container:
        image: "019359803926.dkr.ecr.ap-southeast-2.amazonaws.com/eks:argo-tasks-{{=sprig.trim(inputs.parameters['version-argo-tasks'])}}"
        env:
          - name: AWS_ROLE_CONFIG_PATH
            value: s3://linz-bucket-config/config.json
          - name: GIT_AUTHOR_NAME
            value: "{{=sprig.regexFind(inputs.parameters.repository, inputs.parameters.target)}}[bot]"
          - name: GIT_AUTHOR_EMAIL
            value: "{{=sprig.regexFind(inputs.parameters.repository, inputs.parameters.target)}}@linz.govt.nz"
        volumeMounts:
          - name: secret-volume
            mountPath: "/root/.ssh/"
        command: [node, /app/index.js]
        args:
          [
            "stac",
            "github-import",
            "--source",
            "{{=sprig.trim(inputs.parameters.source)}}",
            "--target",
            "{{=sprig.trim(inputs.parameters.target)}}",
            "--repo-name",
            "linz/{{=sprig.regexFind(inputs.parameters.repository, inputs.parameters.target)}}",
          ]
