on: [push]

jobs:
  lint-format:
    name: Lint and format workflows
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 18.x
        uses: actions/setup-node@v2.2.0
        with:
          node-version: "18.x"

      - name: Install
        run: yarn

      - name: format
        run: yarn format

      - name: Check formatting
        run: git diff --exit-code

  deploy:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    needs: [lint-format]
    name: Deploy workflows into Argo
    # if: github.ref == 'refs/heads/master'

    steps:
      - name: AWS Configure
        uses: aws-actions/configure-aws-credentials@v1.6.1
        with:
          aws-region: ap-southeast-2
          mask-aws-account-id: true
          role-to-assume: ${{ secrets.AWS_EKS_ROLE }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: '1.22'

      - name: Check kubectl
        run: |
          kubectl --version
